apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-client-data
  labels:
    component: elasticsearch
    role: client-data
spec:
  serviceName: elasticsearch-data
  replicas: 2
  selector:
    matchLabels:
      component: elasticsearch
      role: client-data
  template:
    metadata:
      labels:
        component: elasticsearch
        role: client-data
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: role
                  operator: In
                  values:
                  - client-data
              topologyKey: kubernetes.io/hostname
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: es-client-data
        image: quay.io/pires/docker-elasticsearch-kubernetes:6.2.2
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_NAME
          value: es-openstack
        - name: DISCOVERY_SERVICE
          value: es-discovery
        - name: NODE_MASTER
          value: "false"
        - name: NODE_INGEST
          value: "false"
        - name: HTTP_ENABLE
          value: "true"
        - name: ES_JAVA_OPTS
          value: -Xms1g -Xmx1g
        - name: NETWORK_HOST
          value: _site_,_lo_
        resources:
          limits:
            memory: 8Gi
            cpu: "2"
          requests:
            memory: 8Gi
            cpu: 250m
        ports:
        - containerPort: 9300
          name: transport
        - containerPort: 9200
          name: http
        livenessProbe:
          httpGet:
            path: /_cluster/health
            port: http
          initialDelaySeconds: 20
          timeoutSeconds: 5
        volumeMounts:
        - name: storage
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      storageClassName: ceph
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 25Gi
