apiVersion: v1
kind: Service
metadata:
  name: es-trans
  labels:
    component: elasticsearch
    role: client-data
spec:
  selector:
    component: elasticsearch
    role: client-data
  ports:
  - port: 9300
    name: transport
  clusterIP: None

---

apiVersion: v1
kind: Service
metadata:
  name: es-http
  labels:
    component: elasticsearch
    role: client-data
spec:
  selector:
    component: elasticsearch
    role: client-data
  ports:
  - name: http
    port: 80
    targetPort: 9200

---

apiVersion: v1
kind: Service
metadata:
  name: es-discovery
  labels:
    component: elasticsearch
    role: master
spec:
  selector:
    component: elasticsearch
    role: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP
