apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kibana
  labels:
    component: kibana
spec:
  selector:
    component: kibana
  ports:
  - name: http
    port: 80
    targetPort: http
