apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: elk-openstack
    component: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elk-openstack
      component: kibana
  template:
    metadata:
      labels:
        app: elk-openstack
        component: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana-oss:6.2.2
        env:
        - name: CLUSTER_NAME
          value: es-openstack
        - name: ELASTICSEARCH_URL
          value: http://es-http:80
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 5601
          name: kibana-http
