apiVersion: v1
kind: Service
metadata:
  name: accessh
  namespace: oos
  labels:
    app: accessh
spec:
  type: ClusterIP   # NodePort, LoadBalancer
  selector:
    app: accessh
  ports:
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: accessh-home
  namespace: oos
  labels:
    app: accessh
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ceph
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: accessh-cfg
  namespace: oos
  labels:
    app: accessh
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ceph
  resources:
    requests:
      storage: 10Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: oos
  name: accessh
  labels:
    app: accessh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accessh
  template:
    metadata:
      labels:
        app: accessh
    spec:
      containers:
      - name: ssh
        image: docker-registry.cezdata.corp/accessh:latest
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /home
          name: home
        - mountPath: /etc/ssh/authkeys
          name: keys
        - mountPath: /etc/ssh/users
          name: users
          subPath: users
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: accessh-cfg
      - name: home
        persistentVolumeClaim:
          claimName: accessh-home
      - name: keys
        configMap:
          name: accessh-keys
      - name: users
        configMap:
          name: accessh-users
      ports:
      - containerPort: 22
        protocol: TCP
        name: ssh

# vim: et:ts=2:sw=2
