apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: toolbox1
  labels:
    app: toolbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toolbox
  template:
    metadata:
      labels:
        app: toolbox
    spec:
      containers:
      - name: pv-use
        image: docker.io/horakmar/toolbox:latest

# vim: et:ts=2:sw=2
