apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: oos
  name: toolbox3
  labels:
    app: toolbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toolbox
  template:
    metadata:
      labels:
        app: toolbox
    spec:
      containers:
      - name: pv-use
        image: docker-registry.oos.svc.kube5.corp/toolbox:latest
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: repo-rpm

# vim: et:ts=2:sw=2
