apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: oos
  name: toolbox1
  labels:
    app: toolbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toolbox
  template:
    metadata:
      labels:
        app: toolbox
    spec:
      containers:
      - name: pv-use
        image: docker.io/horakmar/toolbox:latest
        volumeMounts:
        - mountPath: /data
          name: pv-storage
      volumes:
      - name: pv-storage
        persistentVolumeClaim:
          claimName: toolbox
      nodeSelector:
        kubernetes.io/hostname: kl010

# vim: et:ts=2:sw=2
