apiVersion: v1
kind: Pod
metadata:
  name: alpine
  labels:
    app: php-test
spec:
  containers:
  - name: alpine
    image: docker.io/alpine:3.7
    command: ["sleep"]
    args: ["1000000"]
    env:
    - name: HTTP_PROXY
      value: "http://http-proxy.cezdata.corp:8080"
#  nodeSelector:
#    role: proxy
