apiVersion: v1
kind: Service
metadata:
  name: php-test
  labels:
    app: 
spec:
  type: ClusterIP   # NodePort, LoadBalancer
  selector:
    app: php-test
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80

# vim: et:ts=2:sw=2
