# Example of usage of persistentVolumeClaim

apiVersion: v1
kind: Pod
metadata:
  name: pvtest
spec:
  containers:
  - name: net4
    image: quay.io/horakmar/nettest:0.3
    command: ["sleep"]
    args: ["1000000"]
    volumeMounts:
    - mountPath: "/mnt/volume"
      name: pv-storage
  volumes:
  - name: pv-storage
    persistentVolumeClaim:
      claimName: pvc1-3g
