apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: kubernetes.io/rbd
  name: pv-dind1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: docker-storage
    namespace: oos
  persistentVolumeReclaimPolicy: Delete
  rbd:
    fsType: ext4
    image: dind1
    keyring: /etc/ceph/keyring
    monitors:
    - 172.28.112.50:6789
    - 172.28.112.51:6789
    - 172.28.112.52:6789
    pool: kube
    secretRef:
      name: ceph-secret-user
    user: kube
  storageClassName: ceph
status:
  phase: Bound
