version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /data
  delete:
    enabled: true
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
  tls:
    certificate: /tls/tls.crt
    key: /tls/tls.key
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
