apiVersion: v1
kind: Secret
metadata:
  name: registry-tls
type: Opaque
data:
  tls.cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQzakNDQXNhZ0F3SUJBZ0lVU3NnNjNZL29kTnBsYjdiLzFSenhxZWllWTVjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd05qRUxNQWtHQTFVRUJoTUNRMW94RURBT0JnTlZCQW9UQjBORldpQkpRMVF4RlRBVEJnTlZCQU1UREVORgpXaUJKUTFRZ1EwRWdNVEFlRncweE56QTVNakF4TkRFNU1EQmFGdzB4T1RBNU1qQXhOREU1TURCYU1Ea3hDekFKCkJnTlZCQVlUQWtOYU1SQXdEZ1lEVlFRS0V3ZERSVm9nU1VOVU1SZ3dGZ1lEVlFRREV3OWtiMk5yWlhJdGNtVm4KYVhOMGNua3dnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDZXh6cTNUMGRSK1FZZgpRdjE2NFhva3R2NzVKMm94UWx2R1FTRVBTUmN2cVpXZjhwcUtmZjZhcHV0bjkzamdhaUFtVXpOZGM4UmZzbU81CnZtNUtIN3gwd2Qrem1qc2VPTk1jYTZSTTVERmFzVG5PY2w5TU5uK045Ui9EeVZsS0tZUE5WcWhTMTQ5Y1Erb2YKTmo1WjdpNWlIK3JlU0dodjdDbWRGUlhlUWVPMHZRMm5uazJ5dlVEQ28yNnpWeXlpS2wxanVFcTdFc0gweEtHQwpjbnUvRmhjcVpHbFdqT2JPb1U0Y1RYT2lVUFhTQmc4SzQzRzZhUmxCZ1pJTTZub3hjdXA0bmg5RW56VEc5eFNjCnhPSkZtbTFtSkkzTHF6bE9TZzZHSnFHdlhkaTdnY1ZNMGM1ZUo1OFNqZFoxRm0vUTBlU3lXY21GSnlLeDRleVMKVlovS0tFb2hBZ01CQUFHamdlQXdnZDB3RGdZRFZSMFBBUUgvQkFRREFnV2dNQk1HQTFVZEpRUU1NQW9HQ0NzRwpBUVVGQndNQk1Bd0dBMVVkRXdFQi93UUNNQUF3SFFZRFZSME9CQllFRk84ZUc1Z2RrVy9sb0FZRUlDZVRlWnArCnQ0dDRNQjhHQTFVZEl3UVlNQmFBRkIwWGZ1eGgxd2dZeE5EcjhGUTRselJ3UWIvMk1HZ0dBMVVkRVFSaE1GK0MKRldSdlkydHlaV2N4TG1ObGVtUmhkR0V1WTI5eWNJSXBaRzlqYTJWeUxYSmxaMmx6ZEhKNUxtUmxabUYxYkhRdQpjM1pqTG1Oc2RYTjBaWEl1Ykc5allXeUNHMlJ2WTJ0bGNpMXlaV2RwYzNSeWVTNWtaV1poZFd4MExuTjJZekFOCkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUhDeWVDNm53WTNYRkxwVXBaN2lZOU9TeUIweXRSRWlqb3N5ZjRIamUKOUV2TlMyUGk5Q0N6N0YwWThkemM3TndBNTRQL3VLcC9EblFEcGZqQnppNWtOcy9PMmhHdHFhOTNnQ1g4YkpTaAoxM2JsT2VvK2FYZ2RVeXhRZ3M4L2UyRlZvdmlPaUZtWTVqdHRTM0htcmo1QVlOTk54ajg4UVNPbktnYWdSV3AyCndzRkVXWnk2QW1jM1VuSjZpd2FUYlBtcEFPVXNJZFVVemxQeUZVN0YxVFVOME53TVFueE9pemgxNVdVOTRvMWgKMG00NG9vdCtvbnEvd2l5TnFBdkpkZnB6dHFBbXhzY0FJc1ZpZEdpL0Fwai9YdUVMck5wSk5NMGVQVmtOR1dkNwp6Q2NLdXFPWHBuRkx6UzJmNVJNblFPaHBOR1JrUk9vZ2l6TDBySHVlL2FBbVpnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBbnNjNnQwOUhVZmtHSDBMOWV1RjZKTGIrK1NkcU1VSmJ4a0VoRDBrWEw2bVZuL0thCmluMyttcWJyWi9kNDRHb2dKbE16WFhQRVg3Smp1YjV1U2grOGRNSGZzNW83SGpqVEhHdWtUT1F4V3JFNXpuSmYKVERaL2pmVWZ3OGxaU2ltRHpWYW9VdGVQWEVQcUh6WStXZTR1WWgvcTNraG9iK3dwblJVVjNrSGp0TDBOcDU1TgpzcjFBd3FOdXMxY3NvaXBkWTdoS3V4TEI5TVNoZ25KN3Z4WVhLbVJwVm96bXpxRk9IRTF6b2xEMTBnWVBDdU54CnVta1pRWUdTRE9wNk1YTHFlSjRmUko4MHh2Y1VuTVRpUlpwdFppU055NnM1VGtvT2hpYWhyMTNZdTRIRlROSE8KWGllZkVvM1dkUlp2ME5Ia3NsbkpoU2Npc2VIc2tsV2Z5aWhLSVFJREFRQUJBb0lCQUdCcGs2TEp0Z0gxbDUwVgovWHRIUFBiY1U3a1JFTzkyWHVua2xHR0d2VmlJdmoxUWdEekdRdnEvanNRanhqZG0yYnpMMnEzTlpSbkM1Y0ZjCisvVndqZXZMNmIxU1VzR0lPZERSSUFROHNDZGs1RGdTeFFFdk9vY0ZxRk1uaVZ0NkYvbHd2R2NKVTVqditGTVoKaWdUcmx5aW9QdUxZenVuZldtbHk2ME41ZVA0K3RSZncwUjNXWEFlaUlaZFFFNWszNnYzNHNoRFhrV3dSU0pFUwpDdjZEeVk3ZXJEbkFHQ3Byeng1R3doOGl2K1g3dzg1ZytGY1ByWWlVQlJqRmtPb28vTFdJMUg1dTJTR3RyRG0xCkZGWXU2WmM0dk1kWkNJSCsrVVlCVzQ3ZWlUdDFhS3Z2TmpsN0tDMHVGUUNkNTJ2VVFwa1c4N2xWQmFKUXpqakgKN2NpVnRvMENnWUVBeTFPUVdld3htdkxkZWxsS21IRFBMais4aVB0MGJJMzJYTWhlY2pETGxYek52R2J3bWMyKwpwQjlFOUFoS0RkQ0ZpZWg1Z0loMTZUeFM2RGtacEVuT3ZteHNjZzI0di9vN0Y5M3FSOXVWSkY1b0xRU2FRVStzCmpJK1NYZG5qUGQxM3VvVTQwVWtEdUl2aTlqWVJic3J6Q1dIOFJ0QzhTdlZsRmVnUWtzdlVBSDhDZ1lFQXgrbEUKamc5SHJ5cEtZQzlNT2l5ak15c1dZZlZJNEZmYmZ6dUJkSTFEWHpaaVdXSEJUY1FDcUh1SUtpSkkxbW5WaHROTAoweWNud3FvZ1lMc2RobWJMeGpYYlh5bGJTMjBKNnJsdDBLRW44TzRLVzhXdk5UUkFFU3Jya0N3bitRb2p1TUFzCnVpWkdkRVNXRy9JdzhvWlZJV2xud01mMHR0NDV5bW00YU5pMlpWOENnWUEwcUg2eEd6KzVubjZIcWtwc2NvTGwKdW5JTWsvc1NCaTR3MTEvR2VTYXduM0wxQVQvOHhWRkRWaW5ZZmJFWUpOSUE1bWxaUlg0c0dvaHFSaWVDNmU2VwpXS1E1WVo1Z2NlRU9ERllacUIvWEhIQWtnSldtcG9qTW1uNVF1aFpsTms5RXlpM3QzZGdOMm9TOE9VS0lqQjBuClorNGJOUUllODdEclhIKzJWUDJoNXdLQmdDMmlJZlFMcU9GalZmYisxUGV5bU01bFY0YWs1eTNPNEZ2NnlXSkIKbk05dktxUWNuSE9UK3NkYTY0b3lxVTNJZXVWNzlpTU5IUlppbjJGMVZSZ0kveHNQMERPNHpRNDZwYmplK3lKVQpwemxvSFJVMTJ2amFKSVhHdGw4Q3RWMHo0MU9aQ3B5emdBR3FabG1hdjNHZEdIRzREZWNEdmVqQWNaQ3k4VlY5Cm9xVWhBb0dCQUpLVzNuVTFXVEozenpiaC9LbWRTeUcvVXR0KzFBeXJnUGNDMGtEdGp2N2pVQlBDQ0pRdXFXZXIKU2dzODFteHJkVG00dWFJZmRic1BQanJ0OWZEOTd4bHZrd2Y5eHVMMkpHcWtIYjAxQjFDVUpTbWZzQ3cyRkpvUQp1WkdiUTk5SVdoRGp4WkJWYUN1TldXVmRGVGJjaUR4cG5LVmRyK1VZcnJYekxYTkpURWVYCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry
  labels:
    app: docker-registry
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: docker-registry
  labels:
    app: docker-registry
spec:
  replicas: 1
  template:
    metadata:
      name: docker-registry
      labels:
        app: docker-registry
    spec:
      containers:
      - name: registry
        image: registry:2
        env:
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /data
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /tls/tls.cert
        - name: REGISTRY_HTTP_TLS_KEY
          value: /tls/tls.key
        volumeMounts:
        - mountPath: /data
          name: registry-data
        - mountPath: /tls
          name: registry-tls
        ports:
        - containerPort: 5000
          protocol: TCP
          name: registry

      volumes:
      - name: registry-tls
        secret:
          secretName: registry-tls
      - name: registry-data
        persistentVolumeClaim:
          claimName: docker-registry

# vim: et:ts=2:sw=2
