kind: ConfigMap
apiVersion: v1
metadata:
  name: docker-auth-config
data:
  auth_config.yml: |
    server:
      addr: ":5001"
      certificate: "/pki/tls.crt"
      key: "/pki/tls.key"

    token:
      issuer: "Cesanta auth server"  # Must match issuer in the Registry config.
      expiration: 900

    users:
      # Password is specified as a BCrypt hash. Use htpasswd -B to generate.
      "admin":
        password: "$2y$05$jXzJ.8H5z0Qpl79TK5hM6OVJB9.YdYh0/31zDRj7WDGTmspzLZzNW"  # Reg5Admin 
      "test":
        password: "$2y$05$WuwBasGDAgr.QCbGIjKJaep4dhxeai9gNZdmBnQXqpKly57oNutya"  # 123
      "user":
        password: "$2y$05$c8onxW4YI/n6wssOBguNKun6yFilC8sPcEGtfyet.H.wjV9sOquMS"  # Pull9Docker
      "": {} # Allow anonymous (no "docker login") access.

    acl:
      - match: {account: "admin"}
        actions: ["*"]
        comment: "Admin has full access to everything."
      - match: {account: "user"}
        actions: ["*"]
        comment: "User can do everything."
      - match: {account: "test"}
        actions: ["pull"]
        comment: "User test can pull stuff."
      - match: {type: "registry", name: "catalog"}
        actions: ["*"]
        comment: "Everyone can read registry."
      - match: {type: "repository"}
        actions: ["pull"]
        comment: "Everyone can pull."
    # Access is denied by default.
 
---
apiVersion: v1
kind: Service
metadata:
  name: docker-auth
spec:
  type: ClusterIP
  selector:
    app: docker-auth
  ports:
  - name: registry-auth
    protocol: TCP
    port: 5001
    targetPort: registry-auth

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-auth
  labels:
    app: docker-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-auth
  template:
    metadata:
      labels:
        app: docker-auth
    spec:
      containers:
      - name: docker-auth
        image: cesanta/docker_auth:1.3
        args: ["--v=2", "--alsologtostderr", "/config/auth_config.yml"]
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /pki
          name: pki
        ports:
        - containerPort: 5001
          protocol: TCP
          name: registry-auth

      volumes:
      - name: config
        configMap:
          name: docker-auth-config
      - name: pki
        secret:
          secretName: docker-auth

# vim: et:ts=2:sw=2
