apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: %app
  namespace: default
  labels:
    app: %app
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: %vol

# vim: et:ts=2:sw=2
