apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: oos
  name: pv-repo-rpm
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 800Gi
  persistentVolumeReclaimPolicy: Retain
  cephfs:
    monitors:
    - 172.28.112.50:6789
    - 172.28.112.51:6789
    - 172.28.112.52:6789
    path: /private/kube5/repo-rpm 
    user: kube5-fs
    secretRef:
      name: cephfs-secret
    readOnly: false
