apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2017-12-29T06:59:57Z
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: KubeDNS
  name: kube-dns
  namespace: kube-system
  resourceVersion: "1208"
  selfLink: /api/v1/namespaces/kube-system/services/kube-dns
  uid: e174c7ce-ec65-11e7-a31a-00237d3511d2
spec:
  clusterIP: 172.28.114.10
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
