apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: caplan-kibana
spec:
  tls:
  - hosts:
    - caplan-kibana.cezdata.corp
    secretName: caplan-kibana-tls
  rules:
  - host: caplan-kibana.cezdata.corp
    http:
      paths:
      - path: /
        backend:
          serviceName: caplan-kibana
          servicePort: 5601
