apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  labels:
    app: zabbix
spec:
  type: ClusterIP   # NodePort, LoadBalancer
  selector:
    app: zabbix
    role: server
  ports:
  - name: zabbix-server
    protocol: TCP
    port: 10051
    targetPort: zabbix-server

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  labels:
    app: zabbix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix
      role: server
  template:
    metadata:
      labels:
        app: zabbix
        role: server
    spec:
      containers:
      - name: zabbix-server
        image: docker-registry.cezdata.corp/zabbix/zabbix-server-pgsql:alpine-3.4.6
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: zabbix-postgres-cred
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zabbix-postgres-cred
              key: password
        - name: DB_SERVER_HOST
          value: zabbix-postgres
        ports:
        - containerPort: 10051
          protocol: TCP
          name: zabbix-server

# vim: et:ts=2:sw=2
