apiVersion: v1
kind: Service
metadata:
  namespace: oos
  name: zabbix1
  labels:
    app: zabbix
spec:
  type: ClusterIP   # NodePort, LoadBalancer
  clusterIP: 172.28.114.21
  selector:
    app: zabbix
    role: web
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  - name: https
    protocol: TCP
    port: 443
    targetPort: https

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: oos
  name: zabbix-web
  labels:
    app: zabbix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix
      role: web
  template:
    metadata:
      labels:
        app: zabbix
        role: web
    spec:
      containers:
      - name: zabbix-web
        image: docker-registry.cezdata.corp/zabbix/zabbix-web-nginx-pgsql:alpine-3.4.6
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: zabbix-postgres-cred
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zabbix-postgres-cred
              key: password
        - name: DB_SERVER_HOST
          value: zabbix-postgres
        - name: ZBX_SERVER_HOST
          value: zabbix-server
        - name: PHP_TZ
          value: Europe/Prague
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
        - containerPort: 443
          protocol: TCP
          name: https
        volumeMounts:
        - mountPath: /etc/ssl/nginx
          name: tls
      volumes:
      - name: tls
        secret:
          secretName: zabbix-web-tls
        
# vim: et:ts=2:sw=2
