apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: torus
  labels:
    app: torus
spec:
  template:
    metadata:
      name: torus
      labels:
        daemon: torus
    spec:
      containers:
      - name: torus
        image: quay.io/coreos/torus:latest
        ports:
        - name: peer
          containerPort: 40000
        - name: http
          containerPort: 4321
        env:
        - name: ETCD_HOST
          value: http://10.83.0.100
        - name: STORAGE_SIZE
          value: 40GiB
        - name: LISTEN_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: AUTO_JOIN
          value: "1"
        - name: DEBUG_INIT
          value: "1"
        - name: DROP_MOUNT_BIN
          value: "0"
        volumeMounts:
        - name: data
          mountPath: /data
          readOnly: false
      volumes:
        - name: data
          hostPath:
            path: /srv/torus
      imagePullSecrets:
        - name: quay-torus
