kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-config
  namespace: kube-system
data:
  fluentd.conf: |
    <source>
       @type tail
       path /var/log/containers/*.log
       pos_file Fluentd-docker.pos
       time_format %Y-%m-%dT%H:%M:%S
       tag kubernetes.*
       format json
       read_from_head true
    </source>
    
    <match **>
       type stdout
    </match>

---

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    app: es-logging
spec:
  template:
    metadata:
      name: fluentd
      labels:
        daemon: fluentd
    spec:
      containers:
      - name: fluentd
        image: fabric8/fluentd-kubernetes:latest
        env:
        - name: ELASTICSEARCH_HOST
          value: es-logging.kube-system.svc
        resources:
          requests:
            memory: 200Mi
            cpu: 100m
          limits:
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config-volume
        configMap:
          name: fluentd-config
          items:
          - key: fluentd.conf
            path: fluentd.conf
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
