apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret-user
type: "kubernetes.io/rbd"  
data:
# Base64 encoded.
  key: QVFCTlR5RmFtYU5qQ2hBQXdzQVBwdVFxaG1iaUgwc21aeDFNVWc9PQ==

---

apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
  namespace: kube-system
type: "kubernetes.io/rbd"  
data:
# Base64 encoded.
  key: QVFCTlR5RmFtYU5qQ2hBQXdzQVBwdVFxaG1iaUgwc21aeDFNVWc9PQ==
