kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ceph
provisioner: kubernetes.io/rbd
parameters:
  monitors: 172.28.112.50:6789,172.28.112.51:6789,172.28.112.52:6789
  adminId: kube
  adminSecretName: ceph-secret-user
  pool: kube
  userId: kube
  userSecretName: ceph-secret-user
  fsType: ext4
  imageFormat: "1"
