kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ceph
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/rbd
parameters:
  monitors: 172.28.112.50:6789,172.28.112.51:6789,172.28.112.52:6789
  adminId: kube6
  adminSecretName: ceph-secret
  adminSecretNamespace: kube-system
  pool: kube6
  userId: kube6
  userSecretName: ceph-secret-user
  fsType: ext4
  imageFormat: "2"
  imageFeatures: "layering"

