apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolbox
  labels:
    app: toolbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toolbox
  template:
    metadata:
      labels:
        app: toolbox
    spec:
      containers:
      - name: pv-use
        image: docker-registry.cezdata.corp/horakmar/toolbox:latest
        volumeMounts:
        - mountPath: /data
          name: pv-storage
      volumes:
      - name: pv-storage
        persistentVolumeClaim:
          claimName: test

# vim: et:ts=2:sw=2
