apiVersion: v1
kind: PersistentVolume
metadata:
  name: snap1
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Delete
  rbd:
    fsType: ext4
    image: kubernetes-dynamic-pvc-dd093f87-f884-11e7-9556-00237d3511d2@snap1
    monitors:
    - 172.28.112.50:6789
    - 172.28.112.51:6789
    - 172.28.112.52:6789
    pool: kube
    secretRef:
      name: ceph-secret-user
    user: kube
    readOnly: false
