apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: kibana
  labels:
    k8s-app: es-logging
    component: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
     k8s-app: es-logging
     component: kibana
  template:
    metadata:
      labels:
        k8s-app: es-logging
        component: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana-oss:6.2.2
        env:
        - name: CLUSTER_NAME
          value: myesdb
        - name: ELASTICSEARCH_URL
          value: http://es-http:80
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 5601
          name: http
