apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: oos
  name: dokuwiki
  labels:
    app: dokuwiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dokuwiki
  template:
    metadata:
      labels:
        app: dokuwiki
    spec:
      containers:
      - name: dokuwiki
        image: docker-registry.cezdata.corp/dokuwiki:0.7
        volumeMounts:
        - mountPath: /data
          name: doku-data
        - mountPath: /etc/nginx/pki
          name: tls
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
        - containerPort: 443
          protocol: TCP
          name: https
      - name: sshd
        image: docker-registry.cezdata.corp/freeze-sshd
        securityContext:
          privileged: true
        env:
        - name: DEBUG
          value: "1"
        volumeMounts:
        - mountPath: /data
          name: doku-data
        - mountPath: /etc/ssh/keys
          name: ssh-keys
        ports:
        - containerPort: 22
          protocol: TCP
          name: ssh
      volumes:
      - name: doku-data
        persistentVolumeClaim:
          claimName: doku-data
      - name: tls
        secret:
          secretName: dokuwiki-tls
      - name: ssh-keys
        secret:
          secretName: dokuwiki-sshd-keys

# vim: et:ts=2:sw=2
