apiVersion: apps/v1
kind: Deployment
metadata:
  name: dokuwiki
  labels:
    app: dokuwiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dokuwiki
  template:
    metadata:
      labels:
        app: dokuwiki
    spec:
      containers:
      - name: dokuwiki
        image: docker.io/rootlogin/dokuwiki:latest
        env:
        - name: INSTALL
          value: "1"
        volumeMounts:
        - mountPath: /data
          name: doku-data
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
        - containerPort: 443
          protocol: TCP
          name: https
      volumes:
      - name: doku-data
        persistentVolumeClaim:
          claimName: doku-data

# vim: et:ts=2:sw=2
