apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: doku-data
  namespace: default
  labels:
    app: dokuwiki
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ceph
  resources:
    requests:
      storage: 5Gi

# vim: et:ts=2:sw=2
