apiVersion: v1
kind: Service
metadata:
  name: dokuwiki
  labels:
    app: dikuwiki
spec:
  type: ClusterIP   # NodePort, LoadBalancer
  selector:
    app: dokuwiki
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  - name: https
    protocol: TCP
    port: 443
    targetPort: https

# vim: et:ts=2:sw=2
