apiVersion: v1
kind: Service
metadata:
  name: %service_name
  labels:
    app: %app
    kubernetes.io/cluster-service: "true"
spec:
  type: ClusterIP   # NodePort, LoadBalancer
  selector:
    app: %app
  ports:
  - name: %port_name
    protocol: TCP
    port: %service_port
    targetPort: %backing_pod_port_can_be_name

# vim: et:ts=2:sw=2
