apiVersion: v1
kind: Service
metadata:
  namespace: oos
  name: dokuwiki1
  labels:
    app: dokuwiki
spec:
  type: ClusterIP   # NodePort, LoadBalancer
  clusterIP: 172.28.114.22
  selector:
    app: dokuwiki
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  - name: https
    protocol: TCP
    port: 443
    targetPort: https
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: ssh

# vim: et:ts=2:sw=2
