apiVersion: v1
kind: Service
metadata:
  name: es-logging
  namespace: kube-system
  labels:
    k8s-app: es-logging
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Elasticsearch"
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: es-port
  selector:
    k8s-app: es-logging


---


apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-logging
  namespace: kube-system
  labels:
    k8s-app: es-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: es-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - image: elasticsearch:alpine
        name: es-logging
        ports:
        - containerPort: 9200
          name: es-port
          protocol: TCP
        - containerPort: 9300
          name: transport-port
          protocol: TCP
        volumeMounts:
        - name: es-persistent-storage
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: es-persistent-storage
        emptyDir: {}
