apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dind
spec:
  replicas: 1
  template:
    metadata:
      name: dind
      labels:
        app: dind
    spec:
        containers:
        - name: dind-daemon
          image: docker.io/horakmar/dind:0.3
          args: ['--storage-driver=overlay']
          env:
          - name: HTTP_PROXY
            value: http://http-proxy.cezdata.corp:8080
          - name: HTTPS_PROXY
            value: http://http-proxy.cezdata.corp:8080
          - name: NO_PROXY
            value: "docker1.cezdata.corp,git.cezdata.corp,ubauto.cezdata.corp,docker-registry.default.svc,docker-auth.default.svc,kl001.cezdata.corp,kl002.cezdata.corp,kl003.cezdata.corp,kl004.cezdata.corp,kl005.cezdata.corp"
          resources:
              requests:
                  cpu: 20m
                  memory: 512Mi
          securityContext:
              privileged: true
          ports:
          - containerPort: 2375
          volumeMounts:
            - name: docker-graph-storage
              mountPath: /var/lib/docker
        volumes:
        - name: docker-storage
          persistentVolumeClaim:
            claimName: docker-storage

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
