apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-graph-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: Pod
metadata:
    name: dind-build
spec:
    containers:
    - name: dind-daemon
      image: horakmar/dind:0.2
      args: ['--storage-driver=overlay']
      env:
      - name: HTTP_PROXY
        value: http://http-proxy.cezdata.corp:8080
      - name: HTTPS_PROXY
        value: http://http-proxy.cezdata.corp:8080
      - name: NO_PROXY
        value: "docker1.cezdata.corp,git.cezdata.corp,ubauto.cezdata.corp,docker-registry.default.svc,docker-auth.default.svc"
      resources:
          requests:
              cpu: 20m
              memory: 512Mi
      securityContext:
          privileged: true
      volumeMounts:
        - name: docker-graph-storage
          mountPath: /var/lib/docker
    volumes:
    - name: docker-graph-storage
      persistentVolumeClaim:
        claimName: docker-graph-storage

# vim: et:ts=2:sw=2
