apiVersion: v1
kind: Service
metadata:
  name: docker1
  labels:
    app: dind
spec:
  type: ClusterIP   # NodePort, LoadBalancer
  clusterIP: 172.28.114.18
  selector:
    app: dind
  ports:
  - name: docker
    port: 2375
    protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dind
  template:
    metadata:
      name: dind
      labels:
        app: dind
    spec:
        containers:
        - name: dind
          image: docker-registry.cezdata.corp/dind:17.12.0-ce.0
          args: ['--storage-driver=overlay']
          env:
          - name: HTTP_PROXY
            value: http://http-proxy.cezdata.corp:8080
          - name: HTTPS_PROXY
            value: http://http-proxy.cezdata.corp:8080
          - name: NO_PROXY
            value: "docker-registry.default.svc,docker-auth.default.svc,docker-auth.cezdata.corp,docker-registry.cezdata.corp,git.cezdata.corp,.cezdata.corp,.default.svc"
          securityContext:
              privileged: true
          ports:
          - containerPort: 2375
          volumeMounts:
            - name: docker-storage
              mountPath: /var/lib/docker
        volumes:
        - name: docker-storage
          persistentVolumeClaim:
            claimName: docker-storage

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-storage
  namespace: default
  labels:
    app: dind
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ceph
  resources:
    requests:
      storage: 20Gi

# vim: et:ts=2:sw=2
