FROM docker-registry.cezdata.corp/backuper

RUN curl -sL https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - \
    && echo "deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main" > /etc/apt/sources.list.d/psql.list \
    && apt-get -q update \
    && apt-get -y install postgresql-client-10 \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY files/backup_zabbix.sh /usr/local/bin/

CMD ["/usr/local/bin/backup_zabbix.sh"]

LABEL version="0.2"
LABEL maintainer="Martin Horak (horak.martin@gmail.com)"
