FROM docker-registry.cezdata.corp/backuper

RUN apt-get -q update \
    && apt-get -y install postgresql-client \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

LABEL version="0.1"
LABEL maintainer="Martin Horak (horak.martin@gmail.com)"
