apiVersion: v1
kind: Service
metadata:
  namespace: pia
  name: backend
  labels:
    app: pia
spec:
  selector:
    app: pia
    tier: backend
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 3000
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pia
  name: pia-back
  labels:
    app: pia
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pia
      tier: backend
  template:
    metadata:
      labels:
        app: pia
        tier: backend
    spec:
      containers:
      - name: pia-backend
        image: docker-registry.cezdata.corp/pia/cnil-pia-back
        env:
        - name: DATABASE_HOST
          value: 'database'
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: credentials
              key: database_username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: database_password
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: credentials
              key: secret_key_base
        ports:
        - containerPort: 3000
          protocol: TCP
          name: pia

