apiVersion: v1
kind: Service
metadata:
  namespace: pia
  name: frontend
  labels:
    app: pia
spec:
  selector:
    app: pia
    tier: frontend
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pia
  name: pia-front
  labels:
    app: pia
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pia
      tier: frontend
  template:
    metadata:
      labels:
        app: pia
        tier: frontend
    spec:
      containers:
      - name: pia-frontend
        image: docker-registry.cezdata.corp/pia/cnil-pia-front
        ports:
        - containerPort: 80
          protocol: TCP
          name: http

