apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: repo1
  labels:
    app: repo1
spec:
  replicas: 1
  template:
    metadata:
      name: repo1
      labels:
        app: repo1
    spec:
      containers:
      - name: nginx
        image: docker.io/nginx:mainline
        volumeMounts:
        - name: data
          mountPath: /usr/share/nginx/html
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: repo1-data

# vim: et:ts=2:sw=2
