apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-harp-www
spec:
  capacity:
    storage: 10Mi 
  accessModes:
  - ReadWriteMany
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  cephfs:
    monitors:
    - 172.28.112.50:6789
    - 172.28.112.51:6789
    - 172.28.112.52:6789
    path: /private/kube5/harp-www
    user: kube5-fs
    secretRef:
      name: cephfs-secret
    readOnly: false
