apiVersion: apps/v1
kind: Deployment
metadata:
  name: cfssl-ca
  labels:
    app: cfssl-ca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cfssl-ca
  template:
    metadata:
      labels:
        app: cfssl-ca
    spec:
      containers:
      - name: cfssl-multirootca
        image: docker-registry.cezdata.corp/cfssl-multirootca:1.2.0
#        command: ["sleep"]
#        args: ["10000000"]
#        args: ["--loglevel", "debug"]
        volumeMounts:
        - mountPath: /etc/multirootca/ca
          name: files
        - mountPath: /etc/multirootca/conf
          name: roots
        ports:
        - containerPort: 8888
          protocol: TCP
          name: cfssl
      volumes:
      - name: files
        secret:
          secretName: cfssl-ca-files
      - name: roots
        configMap:
          name: cfssl-roots

# vim: et:ts=2:sw=2
