apiVersion: v1
kind: PersistentVolume
metadata:
  name: auxiliary1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi1
  iscsi:
     targetPortal: 172.28.113.70
     portals:
     - 172.28.113.71
     iqn: 'iqn.2019-03.kube1:storage01'
     lun: 3
     fsType: 'ext4'
     readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: auxiliary2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi1
  iscsi:
     targetPortal: 172.28.113.70
     portals:
     - 172.28.113.71
     iqn: 'iqn.2019-03.kube1:storage01'
     lun: 4
     fsType: 'ext4'
     readOnly: false

