apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry1
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi1
  iscsi:
     targetPortal: 172.28.113.70
     portals:
     - 172.28.113.71
     iqn: 'iqn.2019-03.kube1:storage01'
     lun: 0
     fsType: 'ext4'
     readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: portus-db1
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi1
  iscsi:
     targetPortal: 172.28.113.70
     portals:
     - 172.28.113.71
     iqn: 'iqn.2019-03.kube1:storage01'
     lun: 1
     fsType: 'ext4'
     readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: portus-db2
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi1
  iscsi:
     targetPortal: 172.28.113.70
     portals:
     - 172.28.113.71
     iqn: 'iqn.2019-03.kube1:storage01'
     lun: 2
     fsType: 'ext4'
     readOnly: false

