apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-alertman
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi1
  iscsi:
     targetPortal: 172.28.113.70
     portals:
     - 172.28.113.71
     iqn: 'iqn.2019-03.kube1:storage01'
     lun: 7
     fsType: 'ext4'
     readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-pushgw
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi1
  iscsi:
     targetPortal: 172.28.113.70
     portals:
     - 172.28.113.71
     iqn: 'iqn.2019-03.kube1:storage01'
     lun: 8
     fsType: 'ext4'
     readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-server
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi1
  iscsi:
     targetPortal: 172.28.113.70
     portals:
     - 172.28.113.71
     iqn: 'iqn.2019-03.kube1:storage01'
     lun: 9
     fsType: 'ext4'
     readOnly: false

