apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
     targetPortal: 172.28.113.70
     portals:
     - 172.28.113.71
     iqn: 'iqn.2019-02.kube01:martin'
     lun: 0
     fsType: 'ext4'
     readOnly: false
