apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
     targetPortal: 172.28.113.70
     iqn: 'iqn.g200-kube01:martin'
     lun: 0
     fsType: 'ext4'
     readOnly: false
