apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
     targetPortal: 172.28.113.70
     portals:
     - 172.28.113.71
     iqn: 'iqn.2019-02.kube01:martin'
     lun: 3
     fsType: 'ext4'
     readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvtest1
  labels:
    app: test1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test1
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
      - name: toolbox
        image: horakmar/toolbox:latest
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc-test1

# vim: et:ts=2:sw=2
