apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvtest
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: toolbox
        image: horakmar/toolbox:latest
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc-test

# vim: et:ts=2:sw=2
