apiVersion: v1
kind: Service
metadata:
  name: repo-apt
  labels:
    app: aptly-repo
spec:
  type: ClusterIP   # NodePort, LoadBalancer
  selector:
    app: aptly-repo
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: ssh


# vim: et:ts=2:sw=2
