apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: kube1-mllb
      protocol: layer2
      addresses:
      - 172.28.112.230-172.28.112.239
