apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repo1-data
  namespace: default
  labels:
    app: repo1
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ceph
  resources:
    requests:
      storage: 50Gi

# vim: et:ts=2:sw=2
