apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lvik
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: docker-registry.cezdata.corp/demo/nginx
        env:
        - name: SERVER_NAME
          value: nginx.lvik.svc.kube6.corp
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
        - containerPort: 443
          protocol: TCP
          name: https
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10       
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
        - mountPath: /etc/nginx/pki
          name: tls
        - mountPath: /etc/nginx/conf.d
          name: confdir
      volumes:
      - name: tls
        secret:
          secretName: nginx-tls
      - name: confdir
        configMap:
          name: nginx-conf-ssl
      - name: html
        persistentVolumeClaim:
          claimName: nginx-html
      
# vim: et:ts=2:sw=2
