apiVersion: v1
kind: Service
metadata:
  namespace: lvik
  name: nginx4
  labels:
    app: nginx4
spec:
  type: ClusterIP   # NodePort, LoadBalancer
  selector:
    app: nginx4
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  - name: https
    protocol: TCP
    port: 443
    targetPort: https

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: lvik
  name: nginx4
  labels:
    app: nginx4
spec:
  serviceName: nginx4
  replicas: 1
  selector:
    matchLabels:
      app: nginx4
  template:
    metadata:
      labels:
        app: nginx4
    spec:
      containers:
      - name: nginx
        image: docker-registry.cezdata.corp/demo/nginx
        env:
        - name: SERVER_NAME
          value: nginx4.lvik.svc.kube6.corp
        resources:
          limits:
            memory: 500Mi
            cpu: 250m
          requests:
            memory: 200Mi
            cpu: 100m
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10       
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
        - mountPath: /etc/nginx/pki
          name: tls
        - mountPath: /etc/nginx/conf.d
          name: confdir
      volumes:
      - name: tls
        secret:
          secretName: nginx4-tls
      - name: confdir
        configMap:
          name: nginx-conf-ssl
  volumeClaimTemplates:
  - metadata:
      name: html
    spec:
      storageClassName: ceph
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 1Gi
