apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lvik
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: docker-registry.cezdata.corp/demo/nginx
        env:
        - name: SERVER_NAME
          value: nginx.lvik.svc.kube6.corp
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
        - mountPath: /etc/nginx/conf.d
          name: confdir
      volumes:
      - name: html
        emptyDir: {}
      - name: confdir
        configMap:
          name: nginx-conf


# vim: et:ts=2:sw=2
