apiVersion: v1
kind: Service
metadata:
  namespace: lvik
  name: nginx
  labels:
    app: nginx
spec:
  type: ClusterIP   # NodePort, LoadBalancer
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  - name: https
    protocol: TCP
    port: 443
    targetPort: https

# vim: et:ts=2:sw=2
