apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: lvik
  name: nginx-html
  labels:
    app: nginx
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ceph
  resources:
    requests:
      storage: 1Gi

# vim: et:ts=2:sw=2

