apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: oos
  name: backuper
  labels:
    app: backuper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backuper
  template:
    metadata:
      labels:
        app: backuper
    spec:
      serviceAccountName: backuper
      hostNetwork: true
      containers:
      - name: backuper
        image: docker-registry.cezdata.corp/backuper
        command: [ "sleep" ]
        args: [ "100000000" ]
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/ceph/ceph.conf
          name: ceph-conf
          subPath: ceph.conf
          readOnly: true
        - mountPath: /etc/ceph/keyring
          name: ceph-keys
          subPath: keyring
          readOnly: true
        - mountPath: /etc/keys/dokuwiki
          name: dokuwiki-keys
          readOnly: true
        - mountPath: /dev
          name: dev
        - mountPath: /lib/modules
          name: modules
      volumes:
      - name: dev
        hostPath:
          path: /dev
      - name: modules
        hostPath:
          path: /lib/modules
      - name: ceph-keys
        secret:
          secretName: ceph-admin-key
      - name: ceph-conf
        configMap:
          name: ceph-config
      - name: dokuwiki-keys
        secret:
          secretName: dokuwiki-sshd-keys
          defaultMode: 0400

# vim: et:ts=2:sw=2
