apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 5Gi
  rbd:
    fsType: ext4
    image: dokuwiki.backup
    monitors:
    - 172.28.112.50:6789
    - 172.28.112.51:6789
    - 172.28.112.52:6789
    pool: kube
    secretRef:
      name: ceph-secret-user
    user: kube
    readOnly: false
