apiVersion: v1
kind: ServiceAccount
metadata:
  name: backuper
  namespace: oos

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: backuper
rules:
  - apiGroups: [""]
    resources:
      - persistentvolumeclaims
      - persistentvolumes
    verbs:
      - get
      - list

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: backuper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backuper
subjects:
- kind: ServiceAccount
  name: backuper
  namespace: oos
