apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: oos
  name: zabbix-backup
spec:
  schedule: "38 0 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: backuper
          containers:
          - name: backuper-psql
            image: docker-registry.cezdata.corp/backuper-psql
            env:
            - name: PGHOST
              value: zabbix-postgres
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: zabbix-postgres-cred
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: zabbix-postgres-cred
                  key: password
            volumeMounts:
            - mountPath: /dbdump
              name: dump
          volumes:
          - name: dump
            emptyDir: {}

# vim: et:ts=2:sw=2
