apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    app: pulp
spec:
  type: ClusterIP
  ports:
  - port: 22
    protocol: TCP
    name: ssh
  selector:
    name: client

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pulp
        name: client
    spec:
      containers:
        - name: client
          image: mhrivnak/pulp-k8s-base:f26
          # imagePullPolicy: Never
          ports:
            - containerPort: 22
          volumeMounts:
            - name: client-cert
              mountPath: /var/run/secrets/pulp/client-cert/
              readOnly: true
            - name: pulp-ca
              mountPath: /var/run/secrets/pulp/pulp-ca/
            - name: logvol
              mountPath: /dev/log
              readOnly: false
      volumes:
        - name: client-cert
          secret:
            secretName: client-cert
        - name: pulp-ca
          configMap:
            name: pulp-ca
        - name: vlp
          persistentVolumeClaim:
            claimName: vlp
        - name: logvol
          emptyDir: {}
