kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: pulp
  name: vlq    # /var/lib/qpidd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph
  resources:
    requests:
      storage: 2Gi
