apiVersion: v1
kind: Pod
metadata:
  name: openstack-base
spec:
  containers:
  - name: testing
    image: quay.io/horakmar/openstack-base
    command: ["sleep"]
    args: ["1000000"]
    volumeMounts:
      - mountPath: /etc/kubernetes/ssl
        name: ssl
        readOnly: true
  volumes:
    - name: ssl
      hostPath:
        path: /etc/kubernetes/ssl
