apiVersion: v1
kind: Service
metadata:
  name: memcached
  labels:
    app: memcached
spec:
  ports:
  - port: 11211
    protocol: TCP
    targetPort: 11211
  selector:
    app: memcached

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: memcached-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
      - name: memcached
        image: memcached
        env:
        - name: MEMCACHED_DUMMY
          value: notused
        ports:
        - containerPort: 11211
