# Kubelet must have access to /usr/sbin/iscsiadm

apiVersion: v1
kind: Pod
metadata:
  name: iscsipd
spec:
  containers:
  - name: net4
    image: quay.io/horakmar/nettest:0.3
    command: ["sleep"]
    args: ["1000000"]
    volumeMounts:
    - mountPath: /etc/kubernetes/ssl
      name: ssl
      readOnly: true
    - mountPath: "/mnt/iscsipd"
      name: iscsipd-rw
  volumes:
  - name: ssl
    hostPath:
      path: /etc/kubernetes/ssl
  - name: iscsipd-rw
    iscsi:
      targetPortal: 172.24.13.28:3260
      iqn: iqn.2017-01.corp.cezdata:k8s
      lun: 1
      fsType: ext4
      readOnly: false
