FROM library/nginx:alpine

COPY files/cez_external_20211025.crt /usr/local/share/ca-certificates/cez_ext.crt
COPY files/cez_internal_20211025.crt /usr/local/share/ca-certificates/cez_int.crt
COPY files/cez_root_20250611.crt /usr/local/share/ca-certificates/cez_root.crt

RUN cat /usr/local/share/ca-certificates/cez_ext.crt /usr/local/share/ca-certificates/cez_int.crt \
  /usr/local/share/ca-certificates/cez_root.crt >> /etc/ssl/cert.pem
