FROM opensuse/portus:2.4

COPY files/cez_external_20211025.crt /usr/local/share/ca-certificates/cez_ext.crt
COPY files/cez_internal_20211025.crt /usr/local/share/ca-certificates/cez_int.crt
COPY files/cez_root_20250611.crt /usr/local/share/ca-certificates/cez_root.crt
COPY files/portus.init /init

RUN chmod +x /init
