apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: oos
  name: repo1
  labels:
    app: repo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repo1
  template:
    metadata:
      labels:
        app: repo1
    spec:
      containers:
      - name: nginx
        image: docker-registry.cezdata.corp/nginx:1.13-alpine.3
        volumeMounts:
        - name: data
          mountPath: /usr/share/nginx/html
        - name: repo1-tls
          mountPath: /etc/nginx/pki
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
        - containerPort: 443
          protocol: TCP
          name: https
      - name: sshd
        image: docker-registry.cezdata.corp/sshd:latest
        env:
        - name: SSH_USERS
          value: "www:101:101"
        - name: MOTD
          value: "Central repository - SSH access"
        volumeMounts:
        - name: data
          mountPath: /repo
        - name: ssh-keys
          mountPath: /etc/authorized_keys
        ports:
        - containerPort: 22
          protocol: TCP
          name: ssh
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: repo1-data
      - name: ssh-keys
        configMap:
          name: repo1-ssh-keys
      - name: repo1-tls
        secret:
          secretName: repo1-tls


# vim: et:ts=2:sw=2
