apiVersion: v1
kind: Service
metadata:
  namespace: oos
  name: repo1
  labels:
    app: repo1
spec:
  type: ClusterIP   # NodePort, LoadBalancer
  selector:
    app: repo1
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  - name: http-tls
    protocol: TCP
    port: 443
    targetPort: https
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: ssh

# vim: et:ts=2:sw=2
