apiVersion: v1
kind: Service
metadata:
  name: repo1
  labels:
    app: repo1
spec:
  type: ClusterIP   # NodePort, LoadBalancer
  selector:
    app: repo1
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: http-tls
    protocol: TCP
    port: 443
    targetPort: 443

# vim: et:ts=2:sw=2
