apiVersion: v1
kind: Pod
metadata:
  labels:
    name: etcd-torus
  name: etcd-torus
spec:
  containers:
  - image: quay.io/coreos/etcd:v3.1.1
    name: etcd-torus
    ports:
    - name: etcd-peers
      containerPort: 2380
    - name: etcd-client
      containerPort: 2379
    volumeMounts:
    - name: data
      mountPath: /var/lib/etcd
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: ETCD_DATA_DIR
      value: /var/lib/etcd
    - name: ETCD_NAME
      value: etcd
    - name: ETCD_INITIAL_CLUSTER
      value: etcd=http://$(POD_IP):2380
    - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
      value: http://$(POD_IP):2380
    - name: ETCD_ADVERTISE_CLIENT_URLS
      value: http://$(POD_IP):2379
    - name: ETCD_LISTEN_CLIENT_URLS
      value: http://0.0.0.0:2379
    - name: ETCD_LISTEN_PEER_URLS
      value: http://$(POD_IP):2380
  volumes:
    - name: data
      emptyDir: {}
