# Prepare:
# kubectl create configmap haproxy-cfg --from-file=haproxy.cfg
# kubectl label nodes nl001 role=manual-proxy

apiVersion: v1
kind: Pod
metadata:
  name: haproxy
spec:
  hostNetwork: true
  containers:
  - name: haproxy
    image: quay.io/horakmar/haproxy:1.7-1
    ports:
    - name: https
      protocol: TCP
      containerPort: 443
      hostPort: 443
    volumeMounts:
    - name: haproxy-cfg
      mountPath: /usr/local/etc/haproxy
  nodeSelector:
    role: manual-proxy
  volumes:
  - name: haproxy-cfg
    configMap:
      name: haproxy-cfg

