kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
      worker_connections 512;
    }
     
    http {
      server {
        listen 80;
        location / {
          proxy_pass http://kibana.kube-system.svc:5601/;
        }
      }
    }

---

apiVersion: v1
kind: Pod
metadata:
  name: service-proxy
spec:
  hostNetwork: true
  containers:
  - name: service-proxy
    image: nginx
    ports:
    - name: http
      protocol: TCP
      containerPort: 80
      hostPort: 80
    volumeMounts:
    - name: config-volume
      mountPath: /etc/nginx
  nodeSelector:
    role: proxy
  volumes:
  - name: config-volume
    configMap:
      name: nginx-config
      items:
      - key: nginx.conf
        path: nginx.conf

