## Bitnami MariaDB configuration
# Image
# ref: https://hub.docker.com/r/bitnami/mariadb/tags/
#
# Installation: helm install --namespace portus --name portus -f mariadb.helm.config.yaml stable/mariadb
#
master:
  persistence:
    size: 4Gi
    storageClass: iscsi1
slave:
  persistence:
    size: 4Gi
    storageClass: iscsi1
db:
  name: portus
  user: portus
  password: SupportuS
rootUser:
  password: SuperMario
replication:
  password: replRapl
