apiVersion: v1
kind: Service
metadata:
  name: portus-nginx
  labels:
    app: portus
    release: "2.4"
spec:
  selector:
    name: portus-nginx
  type: ClusterIP
  ports:
    - name: portus
      port: 443
