apiVersion: v1
kind: ConfigMap
metadata:
  namespace: portus
  name: portus-registry
  labels:
    app: portus
    release: "2.4"
data:
  config: |
    version: 0.1
    loglevel: debug
    storage:
      filesystem:
        rootdirectory: /storage
      delete:
        enabled: true
    http:
      addr: ":5000"
      debug:
        addr: ":5001"
      tls:
        certificate: /certificates/portus.crt
        key: /certificates/portus.key
    auth:
      token:
        realm: https://portus.infra.cl.corp/v2/token
        service: portus.infra.cl.corp
        issuer: portus.kube-system.svc.kube1.cl.corp
        rootcertbundle: /certificates/portus-bundle.crt
    notifications:
      endpoints:
        - name: portus
          url: https://portus.kube-system.svc.kube1.cl.corp:3000/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 5s

