apiVersion: v1
kind: ConfigMap
metadata:
  name: portus-registry
  labels:
    app: portus
    release: "2.4"
data:
  config: |
    version: 0.1
    loglevel: debug
    storage:
      filesystem:
        rootdirectory: /storage
      delete:
        enabled: true
    http:
      addr: ":5000"
      debug:
        addr: ":5001"
      tls:
        certificate: /certificates/portus.crt
        key: /certificates/portus.key
    auth:
      token:
        realm: https://portus-nginx.kube-system.svc.kube1.cl.corp/v2/token
        service: portus-registry:5000
        issuer: portus-2.4
        rootcertbundle: /certificates/portus-bundle.crt
    notifications:
      endpoints:
        - name: portus
          url: https://portus-nginx.kube-system.svc.kube1.cl.corp/v2/webhooks/events
          timeout: 1000ms
          threshold: 5
          backoff: 1s

