apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: portus
  name: portus-registry
  labels:
    storage: portus-registry
    release: "2.4"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: "iscsi1"
