kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: oos
  name: pulp-vlm    # /var/lib/mongodb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph
  resources:
    requests:
      storage: 2Gi
