apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: oos
  name: pv-repo-rpm    # /var/lib/pulp
spec:
  capacity:
    storage: 800Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  cephfs:
    monitors:
    - 172.28.112.50:6789
    - 172.28.112.51:6789
    - 172.28.112.52:6789
    path: /private/kube5/repo-rpm 
    user: kube5-fs
    secretRef:
      name: cephfs-secret
    readOnly: false

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: oos
  name: pulp-vlp    # /var/lib/pulp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  volumeName: pv-repo-rpm
  resources:
    requests:
      storage: 800Gi
